### ISSUE TITLE
Form Element

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#1]
**Value Proposition**

As a user
i want to fill out a form with my data,
so i can create my invoice

![Image](https://user-images.githubusercontent.com/103876505/191215435-efe1f7d0-26d0-4564-be42-e654bb4562af.png)

**Acceptance Criteria**
(describe every scenario in detail) 

- [ ] Filling out the form by the user is required
- [ ]  After pressing submit, it generates an invoice out of the form, which was filled out by the user.

**Tasks** 
(for developers team)

- [ ]  Create a Form
- [ ] Create an Input element for name
- [ ] Create an Input element for Amount
- [ ] Create a submit button

**Comment by OmerAdam34** [comment]
Hi Mate! Nice user story! Happy coding

**Comment by MerleMak** [comment]
Looks great Mate!

**Comment by Murci2022** [comment]
> 

Danke dir Merle!

**Comment by Murci2022** [comment]
> 

Danke dir Omer!
