### ISSUE TITLE
create more input item/service button

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#13]
#As a user,
i want to have an add button on the service/items cards
so i can add multiple items or services.

![Image](https://user-images.githubusercontent.com/103876505/192366899-265c2a6a-ca79-4687-9d31-149c4ebacd0a.png)

**Acceptance Criteria**
(describe every scenario in detail)

- [ ] the user adds more "about your item/service" cards to the form by pressing the add button.

**Tasks**
(for developers team)

- [ ]  create a branch
- [ ]  build an add button on the "about your item/service" card.
- [ ] add an onClick function to the add button wich generates a new "about your item/service" card.
- [ ] add a count function to the  "about your item/service" card.
