### ISSUE TITLE
Input details item/service

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#14]
As a user,
i want to add all the data about my service/items,
so it can be submitted to the invoice.

![Image](https://user-images.githubusercontent.com/103876505/192363953-1451da45-cb38-42c0-8068-d92cea0b5f7e.png)

**Acceptance Criteria**
(describe every scenario in detail)

- [ ] the user adds all the details about his service or items
- [ ] the total price, total VAT and the Grand-total will be automatically calculated after submitting the form.

**Tasks**
(for developers team)

- [ ]  create a branch
- [ ]  build Input fields for the service/items details.
- [ ]  add a function to the form which calculates the  the total price, total VAT and the Grand-total, out of the price, quantity and the actual VAT.
