### ISSUE TITLE
Cancel-Button for the dynamicly created Service-Card

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#17]
#As a user,
i want to have a cancel button on the service/items cards
so i can cancel the  service/items card.

![Image](https://user-images.githubusercontent.com/103876505/193255340-5aa756f7-56de-4e0f-b0dc-a3a92237a1e5.png)

**Acceptance Criteria**
(describe every scenario in detail)

- [x] the user cancels the "about your item/service" card.

**Tasks**
(for developers team)

- [x]  create a branch
- [x]  build a cancel button on the "about your item/service" card.
- [x] add an onClick function to the add button wich cancels the "about your item/service" card.
