### ISSUE TITLE
Starting Page

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#27]
As a user
i want a "let's start" button
so i can create an Invoice without registration as a trial.

![Image](https://user-images.githubusercontent.com/103876505/192342985-9a254f72-b99b-4d3a-9dc6-0694cb6a486d.png)

**Acceptance Criteria**
(describe every scenario in detail) 

- [ ] after pressing the "let's start" button, i land on the createInvoice page.

**Tasks** 
(for developers team)

- [ ] create a branch
- [ ] build a Landing Page
- [ ] create a "let's start" button 
- [ ] add an onClick function to the "let's start" button which takes the user to the createInvoice.js .
