### ISSUE TITLE
Edit Button

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#3]
**Value Proposition**

As a user
i want to have an edit button 
so i can still edit the information on my invoice after submit

![Image](https://user-images.githubusercontent.com/103876505/191748467-2612fe0f-d6fd-4944-9f2e-61fbe038b031.png)

**Acceptance Criteria**
(describe every scenario in detail) 

- [ ] after pressing edit, you can change or edit the information of your invoice.

**Tasks** 
(for developers team)

- [ ] create an edit button
- [ ] add an onClick function to the edit-button to set the setInvoice value back to false.

**Comment by mbosselmann** [comment]
Hi Mate! 
I like your user story. 👍  For the acceptance criteria you could describe in more detail which information of your invoice can be edited after clicking the edit button and show this also in a second wireframe if you like.
For your tasks you need to create a new branch and it could be that another form component is necessary. 🤔
