### ISSUE TITLE
Print Out Button

### ISSUE THREAD

**Issue by Murci2022** [Murci2022/capstone-project#4]
**Value Proposition**

As a user
i want to have an Print Out button 
so i can print out my invoice

![Image](https://user-images.githubusercontent.com/103876505/191765245-cee1a8b1-fbff-41fe-a466-bbcf924d777b.png)

**Acceptance Criteria**
(describe every scenario in detail) 

- [ ] after pressing the print out button, the invoice will be printed out localy on your printer.

**Tasks** 
(for developers team)

- [ ] create a print out button
- [ ] add a print out function (window.print) to the print out-button (inside the code).

**Comment by mbosselmann** [comment]
Hi Mate,
nothing to complain! ;-)
You rock! 🪨
